Create table CVSTEST
(
SSN int(9) NOT NULL Primary Key,
school char(50) NOT NULL,
sex char(1) NOT NULL,
age int(3) NOT NULL,
address char(1) NOT NULL,
famsize char(3) NOT NULL,
Pstatus char(1) NOT NULL,
Medu int(1) NOT NULL,
Fedu int(1) NOT NULL,
Mjob char(50) NOT NULL,
Fjob char(50) NOT NULL,
reason varchar(255) NOT NULL,
guardian varchar(25) NOT NULL,
traveltime int(1) NOT NULL,
studytime int(1) NOT NULL,
failures int (1) NOT NULL,
schoolsup char(3) NOT NULL,
paid char(3) NOT NULL,
activities char(3) NOT NULL,
nursery char(3) NOT NULL,
higher char(3) NOT NULL,
internet char(3) NOT NULL,
romantic char(3) NOT NULL,
famrel int(1) NOT NULL,
freetime int(1) NOT NULL,
goout int(1) NOT NULL,
Dalc int(1) NOT NULL,
Walc int(1) NOT NULL,
health int(1) NOT NULL,
absences int(2) NOT NULL,
G1 int(2) NOT NULL,
G2 int(2) NOT NULL,
G3 int(2) NOT NULL
);
